language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "michelesalvatori"
    token: "e06df00f7dfb777960ebb36b186d34c36db508b0" 

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   #- mvn clean verify
   #- sonar-scanner
   - mvn clean verify sonar:sonar -Pcoverage