language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "michelesalvatori"
    token:
      secure: "3b60b099b9eb81275b7f3872dd5a7ed8df1ecdc1"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar